version: '3.5'
services:
  app:
    container_name: express_blog
    restart: always
    build: .
    volumes:
      - ./uploads:/usr/src/app/uploads
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./site_data:/data/db
    ports:
      - '27017:27017'

  nginx:
    container_name: site-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    ports:
      - '80:80'
volumes:
  site_data:
    external: true

